;wPlayerHomeLocation
DEF HOME_PALLET     EQU 0
DEF HOME_VIRIDIAN   EQU 1
DEF HOME_PEWTER     EQU 2
DEF HOME_CERULEAN   EQU 3
DEF HOME_VERMILION  EQU 4
DEF HOME_LAVENDER   EQU 5
DEF HOME_CELADON    EQU 6
DEF HOME_SAFFRON    EQU 7
DEF HOME_FUCHSIA    EQU 8
DEF HOME_CINNABAR   EQU 9
DEF HOME_INDIGO     EQU 10
