Route1West_Script:
	jp EnableAutoTextBoxDrawing

Route1West_TextPointers:
	def_text_pointers
	dw_const Route1WestMysteryCaveSignText, TEXT_ROUTE1WEST_MYSTERY_CAVE_SIGN

Route1WestMysteryCaveSignText:
	text_far _BillsGardenMysteryCaveSignText
	text_end
