Route0East_Script:
	jp EnableAutoTextBoxDrawing

Route0East_TextPointers:
	def_text_pointers
	dw_const Route0EastMysteryCaveSignText, TEXT_ROUTE_0_EAST_MYSTERY_CAVE_SIGN

Route0EastMysteryCaveSignText:
	text_far _BillsGardenMysteryCaveSignText
	text_end
