RedFishingTilesFront: INCBIN "gfx/overworld/red_fish_front.2bpp"
RedFishingTilesBack:  INCBIN "gfx/overworld/red_fish_back.2bpp"
RedFishingTilesSide:  INCBIN "gfx/overworld/red_fish_side.2bpp"
RedFishingRodTiles:   INCBIN "gfx/overworld/fishing_rod.2bpp"
FTrainerFishingTilesFront: INCBIN "gfx/overworld/ftrainer_fish_front.2bpp"
FTrainerFishingTilesBack:  INCBIN "gfx/overworld/ftrainer_fish_back.2bpp"
FTrainerFishingTilesSide:  INCBIN "gfx/overworld/ftrainer_fish_side.2bpp"
