SECTION "NPC Sprites 1", ROMX

ScientistSprite::        INCBIN "gfx/sprites/scientist.2bpp"
RockerSprite::           INCBIN "gfx/sprites/rocker.2bpp"
SwimmerSprite::          INCBIN "gfx/sprites/swimmer.2bpp"
SafariZoneWorkerSprite:: INCBIN "gfx/sprites/safari_zone_worker.2bpp"
GymGuideSprite::         INCBIN "gfx/sprites/gym_guide.2bpp"
GrampsSprite::           INCBIN "gfx/sprites/gramps.2bpp"
ClerkSprite::            INCBIN "gfx/sprites/clerk.2bpp"
FishingGuruSprite::      INCBIN "gfx/sprites/fishing_guru.2bpp"
GrannySprite::           INCBIN "gfx/sprites/granny.2bpp"
NurseSprite::            INCBIN "gfx/sprites/nurse.2bpp"
LinkReceptionistSprite:: INCBIN "gfx/sprites/link_receptionist.2bpp"
SilphPresidentSprite::   INCBIN "gfx/sprites/silph_president.2bpp"
SilphWorkerMSprite::     INCBIN "gfx/sprites/silph_worker_m.2bpp"
WardenSprite::           INCBIN "gfx/sprites/warden.2bpp"
CaptainSprite::          INCBIN "gfx/sprites/captain.2bpp"
FisherSprite::           INCBIN "gfx/sprites/fisher.2bpp"
KogaSprite::             INCBIN "gfx/sprites/koga.2bpp"
GuardSprite::            INCBIN "gfx/sprites/guard.2bpp"
PokeBallSprite::         INCBIN "gfx/sprites/poke_ball.2bpp"
FossilSprite::           INCBIN "gfx/sprites/fossil.2bpp"
BoulderSprite::          INCBIN "gfx/sprites/boulder.2bpp"
PaperSprite::            INCBIN "gfx/sprites/paper.2bpp"
PokedexSprite::          INCBIN "gfx/sprites/pokedex.2bpp"
ClipboardSprite::        INCBIN "gfx/sprites/clipboard.2bpp"
SnorlaxSprite::          INCBIN "gfx/sprites/snorlax.2bpp"
OldAmberSprite::         INCBIN "gfx/sprites/old_amber.2bpp"
GamblerAsleepSprite::    INCBIN "gfx/sprites/gambler_asleep.2bpp"


SECTION "NPC Sprites 2", ROMX

RedBikeSprite::          INCBIN "gfx/sprites/red_bike.2bpp"
RedSprite::              INCBIN "gfx/sprites/red.2bpp"
BlueSprite::             INCBIN "gfx/sprites/blue.2bpp"
OakSprite::              INCBIN "gfx/sprites/oak.2bpp"
YoungsterSprite::        INCBIN "gfx/sprites/youngster.2bpp"
MonsterSprite::          INCBIN "gfx/sprites/monster.2bpp"
CooltrainerFSprite::     INCBIN "gfx/sprites/cooltrainer_f.2bpp"
CooltrainerMSprite::     INCBIN "gfx/sprites/cooltrainer_m.2bpp"
LittleGirlSprite::       INCBIN "gfx/sprites/little_girl.2bpp"
BirdSprite::             INCBIN "gfx/sprites/bird.2bpp"
MiddleAgedManSprite::    INCBIN "gfx/sprites/middle_aged_man.2bpp"
GamblerSprite::          INCBIN "gfx/sprites/gambler.2bpp"
SuperNerdSprite::        INCBIN "gfx/sprites/super_nerd.2bpp"
GirlSprite::             INCBIN "gfx/sprites/girl.2bpp"
HikerSprite::            INCBIN "gfx/sprites/hiker.2bpp"
BeautySprite::           INCBIN "gfx/sprites/beauty.2bpp"
GentlemanSprite::        INCBIN "gfx/sprites/gentleman.2bpp"
DaisySprite::            INCBIN "gfx/sprites/daisy.2bpp"
BikerSprite::            INCBIN "gfx/sprites/biker.2bpp"
SailorSprite::           INCBIN "gfx/sprites/sailor.2bpp"
CookSprite::             INCBIN "gfx/sprites/cook.2bpp"
BikeShopClerkSprite::    INCBIN "gfx/sprites/bike_shop_clerk.2bpp"
MrFujiSprite::           INCBIN "gfx/sprites/mr_fuji.2bpp"
GiovanniSprite::         INCBIN "gfx/sprites/giovanni.2bpp"
RocketSprite::           INCBIN "gfx/sprites/rocket.2bpp"
ChannelerSprite::        INCBIN "gfx/sprites/channeler.2bpp"
WaiterSprite::           INCBIN "gfx/sprites/waiter.2bpp"
SilphWorkerFSprite::     INCBIN "gfx/sprites/silph_worker_f.2bpp"
MiddleAgedWomanSprite::  INCBIN "gfx/sprites/middle_aged_woman.2bpp"
BrunetteGirlSprite::     INCBIN "gfx/sprites/brunette_girl.2bpp"
LanceSprite::            INCBIN "gfx/sprites/lance.2bpp"
MomSprite::              INCBIN "gfx/sprites/mom.2bpp"
BaldingGuySprite::       INCBIN "gfx/sprites/balding_guy.2bpp"
LittleBoySprite::        INCBIN "gfx/sprites/little_boy.2bpp"
GameboyKidSprite::       INCBIN "gfx/sprites/gameboy_kid.2bpp"
FairySprite::            INCBIN "gfx/sprites/fairy.2bpp"
AgathaSprite::           INCBIN "gfx/sprites/agatha.2bpp"
BrunoSprite::            INCBIN "gfx/sprites/bruno.2bpp"
LoreleiSprite::          INCBIN "gfx/sprites/lorelei.2bpp"
SeelSprite::             INCBIN "gfx/sprites/seel.2bpp"


SECTION "NPC Sprites 3", ROMX

LaprasSprite::                  INCBIN "gfx/new_sprites/lapras.2bpp"
SurfingPikachuSprite::          INCBIN "gfx/new_sprites/surfing_pikachu.2bpp"

BillSprite::                    INCBIN "gfx/new_sprites/bill.2bpp"
BlaineSprite::                  INCBIN "gfx/new_sprites/blaine.2bpp"
BrockSprite::                   INCBIN "gfx/new_sprites/brock.2bpp"
BugCatcherSprite::              INCBIN "gfx/new_sprites/bug_catcher.2bpp"
BulbasaurSprite::               INCBIN "gfx/new_sprites/bulbasaur.2bpp"
ChanseySprite::                 INCBIN "gfx/new_sprites/chansey.2bpp"
ErikaSprite::                   INCBIN "gfx/new_sprites/erika.2bpp"
JigglypuffSprite::              INCBIN "gfx/new_sprites/jigglypuff.2bpp"
KogaGen2Sprite::                INCBIN "gfx/new_sprites/koga.2bpp"
MistySprite::                   INCBIN "gfx/new_sprites/misty.2bpp"
NurseJoySprite::                INCBIN "gfx/new_sprites/nurse.2bpp"
OddishSprite::                  INCBIN "gfx/new_sprites/oddish.2bpp"
OfficerJennySprite::            INCBIN "gfx/new_sprites/officer_jenny.2bpp"
PikachuSprite::                 INCBIN "gfx/new_sprites/pikachu.2bpp"
PoliwrathSprite::               INCBIN "gfx/new_sprites/poliwrath.2bpp"
RocketGirlSprite::              INCBIN "gfx/new_sprites/rocket_girl.2bpp"
SandshrewSprite::               INCBIN "gfx/new_sprites/sandshrew.2bpp"
SurgeSprite::                   INCBIN "gfx/new_sprites/surge.2bpp"
SwimmerGirlSprite::             INCBIN "gfx/new_sprites/swimmer_girl.2bpp"

GoldTrophySprite::              INCBIN "gfx/new_sprites/gold_trophy.2bpp"
SlowpokeSprite::                INCBIN "gfx/new_sprites/slowpoke.2bpp"
FuchsiaMonSprite::              INCBIN "gfx/new_sprites/fuchsia_mon.2bpp"


SECTION "MonIcons", ROMX

MonIcons::

NullIcon::         INCBIN "gfx/icons_gen2/null.2bpp"
PoliwagIcon::      INCBIN "gfx/icons_gen2/poliwag.2bpp"
JigglypuffIcon::   INCBIN "gfx/icons_gen2/jigglypuff.2bpp"
DiglettIcon::      INCBIN "gfx/icons_gen2/diglett.2bpp"
PikachuIcon::      INCBIN "gfx/icons_gen2/pikachu.2bpp"
StaryuIcon::       INCBIN "gfx/icons_gen2/staryu.2bpp"
FishIcon::         INCBIN "gfx/icons_gen2/fish.2bpp"
BirdIcon::         INCBIN "gfx/icons_gen2/bird.2bpp"
MonsterIcon::      INCBIN "gfx/icons_gen2/monster.2bpp"
ClefairyIcon::     INCBIN "gfx/icons_gen2/clefairy.2bpp"
OddishIcon::       INCBIN "gfx/icons_gen2/oddish.2bpp"
BugIcon::          INCBIN "gfx/icons_gen2/bug.2bpp"
GhostIcon::        INCBIN "gfx/icons_gen2/ghost.2bpp"
LaprasIcon::       INCBIN "gfx/icons_gen2/lapras.2bpp"
HumanshapeIcon::   INCBIN "gfx/icons_gen2/humanshape.2bpp"
FoxIcon::          INCBIN "gfx/icons_gen2/fox.2bpp"
EquineIcon::       INCBIN "gfx/icons_gen2/equine.2bpp"
ShellIcon::        INCBIN "gfx/icons_gen2/shell.2bpp"
BlobIcon::         INCBIN "gfx/icons_gen2/blob.2bpp"
SerpentIcon::      INCBIN "gfx/icons_gen2/serpent.2bpp"
VoltorbIcon::      INCBIN "gfx/icons_gen2/voltorb.2bpp"
SquirtleIcon::     INCBIN "gfx/icons_gen2/squirtle.2bpp"
BulbasaurIcon::    INCBIN "gfx/icons_gen2/bulbasaur.2bpp"
CharmanderIcon::   INCBIN "gfx/icons_gen2/charmander.2bpp"
CaterpillarIcon::  INCBIN "gfx/icons_gen2/caterpillar.2bpp"
GeodudeIcon::      INCBIN "gfx/icons_gen2/geodude.2bpp"
FighterIcon::      INCBIN "gfx/icons_gen2/fighter.2bpp"
JellyfishIcon::    INCBIN "gfx/icons_gen2/jellyfish.2bpp"
MothIcon::         INCBIN "gfx/icons_gen2/moth.2bpp"
BatIcon::          INCBIN "gfx/icons_gen2/bat.2bpp"
SnorlaxIcon::      INCBIN "gfx/icons_gen2/snorlax.2bpp"
GyaradosIcon::     INCBIN "gfx/icons_gen2/gyarados.2bpp"
SlowpokeIcon::     INCBIN "gfx/icons_gen2/slowpoke.2bpp"
BigmonIcon::       INCBIN "gfx/icons_gen2/bigmon.2bpp"
